"use strict";

// Configuration and runtime state.
const CHIP_ID = "ukrtube-chip";
const SECTION_ID = "ukrtube-section";
const PAGE_SIZE = 30;
const SETTINGS_KEY = "ukrtubeFeedFilters";
const LEGACY_SETTINGS_KEY = "ukrainianFeedFilters";
const SHOW_AI_CONTROLS = false;

const CATEGORIES = [
  {
    id: "news",
    label: "Новини",
    keywords: [
      "новини",
      "news",
      "суспільне",
      "телемарафон",
      "ефір",
      "репортаж",
      "журналіст",
      "breaking",
    ],
  },
  {
    id: "war-politics",
    label: "Війна і політика",
    keywords: [
      "війна",
      "зсу",
      "фронт",
      "армія",
      "ракета",
      "дрон",
      "обстріл",
      "політика",
      "президент",
      "рада",
      "уряд",
      "вибори",
      "трамп",
      "путін",
      "росія",
    ],
  },
  {
    id: "music",
    label: "Музика",
    keywords: [
      "музика",
      "пісня",
      "кліп",
      "альбом",
      "концерт",
      "співає",
      "cover",
      "music",
      "official video",
      "lyrics",
      "караоке",
    ],
  },
  {
    id: "entertainment",
    label: "Розваги",
    keywords: [
      "шоу",
      "гумор",
      "комедія",
      "прикол",
      "розваги",
      "реакція",
      "інтерв'ю",
      "подкаст",
      "стендап",
      "серіал",
      "фільм",
      "кіно",
    ],
  },
  {
    id: "education",
    label: "Освіта",
    keywords: [
      "урок",
      "навчання",
      "освіта",
      "лекція",
      "пояснення",
      "історія",
      "математика",
      "фізика",
      "англійська",
      "курс",
      "tutorial",
      "how to",
    ],
  },
  {
    id: "technology",
    label: "Технології",
    keywords: [
      "технології",
      "штучний інтелект",
      "ai",
      "смартфон",
      "ноутбук",
      "комп'ютер",
      "програмування",
      "огляд гаджет",
      "iphone",
      "android",
      "software",
    ],
  },
  {
    id: "gaming",
    label: "Ігри",
    keywords: [
      "гра",
      "ігри",
      "геймплей",
      "стрім",
      "minecraft",
      "fortnite",
      "roblox",
      "steam",
      "playstation",
      "xbox",
      "gaming",
      "летсплей",
    ],
  },
  {
    id: "kids",
    label: "Дітям",
    keywords: [
      "діти",
      "дитяч",
      "мультфільм",
      "мультик",
      "казка",
      "пісеньки",
      "розвиваюч",
      "малюки",
      "kids",
      "cartoon",
    ],
  },
  {
    id: "sports",
    label: "Спорт",
    keywords: [
      "спорт",
      "футбол",
      "бокс",
      "баскетбол",
      "теніс",
      "матч",
      "гол",
      "чемпіонат",
      "олімпіада",
      "тренування",
      "fitness",
    ],
  },
  {
    id: "food",
    label: "Їжа",
    keywords: [
      "рецепт",
      "готую",
      "кухня",
      "страва",
      "їжа",
      "випічка",
      "салат",
      "торт",
      "сніданок",
      "cooking",
      "recipe",
    ],
  },
  {
    id: "travel",
    label: "Подорожі",
    keywords: [
      "подорож",
      "туризм",
      "мандрів",
      "країна",
      "місто",
      "готель",
      "відпочинок",
      "travel",
      "vlog",
      "екскурсія",
    ],
  },
  {
    id: "business",
    label: "Бізнес і гроші",
    keywords: [
      "бізнес",
      "гроші",
      "фінанси",
      "економіка",
      "інвестиції",
      "заробіток",
      "ринок",
      "крипто",
      "податки",
      "підприємець",
    ],
  },
];

const DATE_PRESETS = [
  { value: "any", label: "Будь-коли" },
  { value: "day", label: "24 години" },
  { value: "week", label: "7 днів" },
  { value: "month", label: "30 днів" },
  { value: "three-months", label: "3 місяці" },
  { value: "year", label: "Рік" },
  { value: "older-year", label: "Старіші" },
  { value: "custom", label: "Свій період" },
];

const DEFAULT_FILTERS = Object.freeze({
  categoryModes: {},
  includeKeywords: "",
  excludeKeywords: "",
  datePreset: "any",
  dateFrom: "",
  dateTo: "",
  aiEnabled: false,
  aiRule: "",
});

function createDefaultFilters() {
  return { ...DEFAULT_FILTERS, categoryModes: {} };
}

const state = {
  active: false,
  loading: false,
  filtersOpen: false,
  lastUrl: location.href,
  videos: [],
  videoIds: new Set(),
  pendingMetadata: 0,
  hasMore: true,
  filters: createDefaultFilters(),
  aiResults: new Map(),
  aiProcessing: false,
  aiStatus: "AI вимкнено",
  aiGeneration: 0,
  loadGeneration: 0,
  metadataGeneration: 0,
  initialized: false,
};

let infiniteScrollObserver = null;
